export type Platform = "PC" | "PS5" | "PS4" | "Xbox" | "Switch" | "iOS" | "Android"

export type Game = {
  slug: string
  title: string
  developer: string
  category: string
  categories: string[]
  platforms: Platform[]
  rating: number
  reviews: number
  description: string
  longDescription: string
  features: string[]
  version: string
  fileSize: string
  lastUpdated: string
  releaseYear: number
  art: string
  featured?: boolean
  trending?: boolean
  mobile?: boolean
  accent: string
}

// Each game uses a single generated artwork (used for cover, thumbnail, and hero).
const img = (slug: string) => `/games/${slug}.png`

export const GAMES: Game[] = [
  {
    slug: "gta-v",
    title: "Grand Theft Auto V",
    developer: "Rockstar Games",
    category: "Action",
    categories: ["Action", "Adventure", "Multiplayer"],
    platforms: ["PC", "PS5", "PS4", "Xbox"],
    rating: 4.8,
    reviews: 184230,
    description: "Explore the sprawling sun-soaked city of Los Santos across three unforgettable criminal lives.",
    longDescription:
      "Grand Theft Auto V blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of three unique characters. The world of Los Santos and Blaine County is bigger, deeper, and more alive than anything Rockstar has built before, with a thriving online component in GTA Online.",
    features: ["Three playable protagonists", "Massive open world", "GTA Online multiplayer", "Heist missions", "Deep customization"],
    version: "1.68",
    fileSize: "94 GB",
    lastUpdated: "May 2026",
    releaseYear: 2013,
    art: img("gta-v"),
    featured: true,
    trending: true,
    accent: "oklch(0.7 0.18 150)",
  },
  {
    slug: "gta-vi",
    title: "Grand Theft Auto VI",
    developer: "Rockstar Games",
    category: "Action",
    categories: ["Action", "Adventure", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    rating: 4.9,
    reviews: 52110,
    description: "Return to the neon-soaked streets of Vice City in the most anticipated open world ever made.",
    longDescription:
      "Grand Theft Auto VI takes players back to the state of Leonida, home to the streets of Vice City and beyond. With its dual-protagonist narrative and a living, breathing world rendered in stunning detail, it sets a new benchmark for open-world games.",
    features: ["Next-gen open world", "Dual protagonists", "Living simulated city", "Dynamic weather", "Reimagined Vice City"],
    version: "1.0",
    fileSize: "150 GB",
    lastUpdated: "Apr 2026",
    releaseYear: 2026,
    art: img("gta-vi"),
    featured: true,
    trending: true,
    accent: "oklch(0.7 0.2 350)",
  },
  {
    slug: "minecraft",
    title: "Minecraft",
    developer: "Mojang Studios",
    category: "Sandbox",
    categories: ["Sandbox", "Adventure", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox", "Switch", "iOS", "Android"],
    rating: 4.7,
    reviews: 321540,
    description: "Build, explore, and survive in an infinite world of blocks limited only by your imagination.",
    longDescription:
      "Minecraft is a game about placing blocks and going on adventures. Explore randomly generated worlds and build amazing things from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode.",
    features: ["Infinite procedural worlds", "Creative & survival modes", "Cross-platform multiplayer", "Redstone engineering", "Endless mods"],
    version: "1.21",
    fileSize: "1.2 GB",
    lastUpdated: "Mar 2026",
    releaseYear: 2011,
    art: img("minecraft"),
    featured: true,
    trending: true,
    mobile: true,
    accent: "oklch(0.7 0.18 150)",
  },
  {
    slug: "spider-man-2",
    title: "Marvel's Spider-Man 2",
    developer: "Insomniac Games",
    category: "Action",
    categories: ["Action", "Adventure"],
    platforms: ["PS5", "PC"],
    rating: 4.8,
    reviews: 98720,
    description: "Swing through a stunning New York as Peter Parker and Miles Morales face their greatest threat.",
    longDescription:
      "Marvel's Spider-Man 2 raises the stakes as Peter Parker and Miles Morales return for an exhilarating new adventure. Swing, jump, and use the new web wings to travel across an expanded Marvel's New York while facing the ultimate test of strength against the symbiote.",
    features: ["Two playable Spider-Men", "Expanded open city", "Web wings traversal", "Symbiote powers", "Cinematic story"],
    version: "1.4",
    fileSize: "98 GB",
    lastUpdated: "Feb 2026",
    releaseYear: 2023,
    art: img("spider-man-2"),
    featured: true,
    trending: true,
    accent: "oklch(0.62 0.23 25)",
  },
  {
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    category: "Adventure",
    categories: ["Adventure", "Action", "RPG"],
    platforms: ["PC", "PS5", "PS4", "Xbox"],
    rating: 4.9,
    reviews: 156890,
    description: "Live the life of an outlaw in a vast, breathtaking recreation of the dying American frontier.",
    longDescription:
      "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal, and fight their way across the rugged heartland of America in order to survive.",
    features: ["Immersive open frontier", "Deep story campaign", "Red Dead Online", "Living ecosystem", "Honor system"],
    version: "1.32",
    fileSize: "120 GB",
    lastUpdated: "Jan 2026",
    releaseYear: 2018,
    art: img("red-dead-redemption-2"),
    featured: true,
    trending: true,
    accent: "oklch(0.65 0.2 50)",
  },
  {
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    category: "RPG",
    categories: ["RPG", "Action", "Adventure"],
    platforms: ["PC", "PS5", "Xbox"],
    rating: 4.6,
    reviews: 142300,
    description: "Become a cyber-enhanced mercenary in the dystopian sprawl of Night City.",
    longDescription:
      "Cyberpunk 2077 is an open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour, and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
    features: ["Branching narrative", "Deep RPG systems", "Cybernetic upgrades", "Phantom Liberty expansion", "Living Night City"],
    version: "2.2",
    fileSize: "100 GB",
    lastUpdated: "Apr 2026",
    releaseYear: 2020,
    art: img("cyberpunk-2077"),
    featured: true,
    trending: true,
    accent: "oklch(0.78 0.18 90)",
  },
  {
    slug: "fortnite",
    title: "Fortnite",
    developer: "Epic Games",
    category: "Multiplayer",
    categories: ["Multiplayer", "Action"],
    platforms: ["PC", "PS5", "Xbox", "Switch", "iOS", "Android"],
    rating: 4.5,
    reviews: 289000,
    description: "Drop in, build, and battle to be the last one standing in the world's biggest battle royale.",
    longDescription:
      "Fortnite is the ever-evolving battle royale phenomenon where 100 players fight to be the last one standing. Build structures, master your loadout, and experience constant new seasons, collaborations, and game modes.",
    features: ["100-player battle royale", "Building mechanics", "Seasonal content", "Creative mode", "Cross-platform play"],
    version: "29.10",
    fileSize: "40 GB",
    lastUpdated: "May 2026",
    releaseYear: 2017,
    art: img("fortnite"),
    trending: true,
    accent: "oklch(0.7 0.16 230)",
  },
  {
    slug: "roblox",
    title: "Roblox",
    developer: "Roblox Corporation",
    category: "Sandbox",
    categories: ["Sandbox", "Multiplayer", "Adventure"],
    platforms: ["PC", "Xbox", "iOS", "Android"],
    rating: 4.4,
    reviews: 412000,
    description: "Play millions of community-made experiences or build your own world to share.",
    longDescription:
      "Roblox is the ultimate virtual universe that lets you create, share experiences with friends, and be anything you can imagine. Join millions of people and explore an infinite variety of immersive, user-generated 3D worlds.",
    features: ["Millions of experiences", "Create your own games", "Massive community", "Avatar customization", "Cross-platform"],
    version: "2.6",
    fileSize: "2.8 GB",
    lastUpdated: "May 2026",
    releaseYear: 2006,
    art: img("roblox"),
    trending: true,
    mobile: true,
    accent: "oklch(0.65 0.05 270)",
  },
  {
    slug: "rocket-league",
    title: "Rocket League",
    developer: "Psyonix",
    category: "Sports",
    categories: ["Sports", "Multiplayer", "Racing"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    rating: 4.6,
    reviews: 176500,
    description: "Soccer meets driving in this high-octane, physics-based competitive sports game.",
    longDescription:
      "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem. Customize your car, hit the pitch, and compete in one of the most critically acclaimed sports games of all time.",
    features: ["Soccer with rocket cars", "Ranked competitive", "Deep car customization", "Cross-platform play", "Free to play"],
    version: "2.40",
    fileSize: "23 GB",
    lastUpdated: "Apr 2026",
    releaseYear: 2015,
    art: img("rocket-league"),
    trending: true,
    accent: "oklch(0.7 0.16 230)",
  },
  {
    slug: "ea-fc-26",
    title: "EA SPORTS FC 26",
    developer: "EA Sports",
    category: "Sports",
    categories: ["Sports", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox", "Switch"],
    rating: 4.3,
    reviews: 88400,
    description: "The world's game returns with the most authentic football experience yet.",
    longDescription:
      "EA SPORTS FC 26 delivers the most true-to-football experience with HyperMotion technology, authentic clubs and leagues, Ultimate Team, and career modes. Step onto the pitch and live the beautiful game.",
    features: ["Authentic clubs & leagues", "Ultimate Team", "HyperMotion gameplay", "Career mode", "Online seasons"],
    version: "1.0",
    fileSize: "55 GB",
    lastUpdated: "May 2026",
    releaseYear: 2025,
    art: img("ea-fc-26"),
    trending: true,
    accent: "oklch(0.7 0.18 150)",
  },
  {
    slug: "call-of-duty",
    title: "Call of Duty",
    developer: "Activision",
    category: "Action",
    categories: ["Action", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    rating: 4.4,
    reviews: 203100,
    description: "Intense, cinematic warfare with a legendary multiplayer and battle royale.",
    longDescription:
      "Call of Duty delivers a blockbuster campaign, fan-favorite multiplayer, and the massive free-to-play Warzone battle royale. Gear up, drop in, and prove yourself across the most competitive shooter franchise in gaming.",
    features: ["Cinematic campaign", "Ranked multiplayer", "Warzone battle royale", "Co-op modes", "Seasonal content"],
    version: "1.12",
    fileSize: "125 GB",
    lastUpdated: "May 2026",
    releaseYear: 2025,
    art: img("call-of-duty"),
    trending: true,
    accent: "oklch(0.68 0.16 60)",
  },
  {
    slug: "rematch",
    title: "Rematch",
    developer: "Sloclap",
    category: "Sports",
    categories: ["Sports", "Multiplayer"],
    platforms: ["PC", "PS5", "Xbox"],
    rating: 4.5,
    reviews: 21450,
    description: "A fast-paced 5v5 football experience where you control a single player on the pitch.",
    longDescription:
      "Rematch reinvents online football. Control a single player in fluid 5v5 matches, master skill-based controls, and chain together team plays in fast, end-to-end action with no fouls, offsides, or interruptions.",
    features: ["Skill-based 5v5", "Single player control", "Fluid controls", "Team play focus", "Ranked ladders"],
    version: "1.0",
    fileSize: "18 GB",
    lastUpdated: "Apr 2026",
    releaseYear: 2026,
    art: img("rematch"),
    trending: true,
    accent: "oklch(0.7 0.16 230)",
  },
  {
    slug: "brawl-stars",
    title: "Brawl Stars",
    developer: "Supercell",
    category: "Multiplayer",
    categories: ["Multiplayer", "Action"],
    platforms: ["iOS", "Android"],
    rating: 4.6,
    reviews: 198000,
    description: "Fast 3v3 mobile battles and a roster of explosive brawlers to master.",
    longDescription:
      "Brawl Stars is a fast-paced multiplayer mobile game featuring 3v3 battles and battle royale modes. Unlock and upgrade dozens of unique brawlers, each with their own signature attacks and super abilities.",
    features: ["3v3 quick matches", "Battle royale mode", "Dozens of brawlers", "Ranked play", "Regular events"],
    version: "55.0",
    fileSize: "350 MB",
    lastUpdated: "May 2026",
    releaseYear: 2018,
    art: img("brawl-stars"),
    mobile: true,
    accent: "oklch(0.78 0.16 80)",
  },
  {
    slug: "clash-royale",
    title: "Clash Royale",
    developer: "Supercell",
    category: "Multiplayer",
    categories: ["Multiplayer"],
    platforms: ["iOS", "Android"],
    rating: 4.4,
    reviews: 224000,
    description: "Real-time tower-rush strategy with collectible cards and competitive ladders.",
    longDescription:
      "Clash Royale is a real-time multiplayer game where you collect cards featuring the Clash of Clans troops, spells, and defenses. Build your battle deck, destroy opponent towers, and climb the global ladder.",
    features: ["Real-time duels", "Collectible card decks", "Clan wars", "Ranked ladder", "Frequent updates"],
    version: "8.1",
    fileSize: "280 MB",
    lastUpdated: "Apr 2026",
    releaseYear: 2016,
    art: img("clash-royale"),
    mobile: true,
    accent: "oklch(0.7 0.16 230)",
  },
  {
    slug: "asphalt",
    title: "Asphalt Legends",
    developer: "Gameloft",
    category: "Racing",
    categories: ["Racing", "Multiplayer"],
    platforms: ["iOS", "Android", "Switch"],
    rating: 4.3,
    reviews: 167000,
    description: "Arcade racing at breakneck speed with a garage full of real licensed hypercars.",
    longDescription:
      "Asphalt Legends delivers console-quality arcade racing on mobile. Collect over 100 high-performance cars, perform gravity-defying stunts, and race against players from around the world in stunning locations.",
    features: ["100+ licensed cars", "Nitro stunt racing", "Online multiplayer", "Career mode", "Stunning tracks"],
    version: "12.5",
    fileSize: "2.5 GB",
    lastUpdated: "Mar 2026",
    releaseYear: 2018,
    art: img("asphalt"),
    mobile: true,
    accent: "oklch(0.62 0.23 25)",
  },
  {
    slug: "call-of-duty-mobile",
    title: "Call of Duty: Mobile",
    developer: "Activision",
    category: "Action",
    categories: ["Action", "Multiplayer"],
    platforms: ["iOS", "Android"],
    rating: 4.5,
    reviews: 256000,
    description: "The full Call of Duty multiplayer experience, optimized for your phone.",
    longDescription:
      "Call of Duty: Mobile brings iconic maps, modes, and weapons from the franchise to mobile. Play classic 5v5 multiplayer, battle royale, and ranked seasons anytime, anywhere.",
    features: ["Iconic CoD maps", "Battle royale", "5v5 multiplayer", "Ranked seasons", "Console-quality controls"],
    version: "1.0.45",
    fileSize: "2.2 GB",
    lastUpdated: "May 2026",
    releaseYear: 2019,
    art: img("call-of-duty-mobile"),
    mobile: true,
    accent: "oklch(0.68 0.16 60)",
  },
]

export const CATEGORIES = [
  { name: "Action", description: "High-octane combat, shooters, and adrenaline-fueled gameplay.", icon: "Swords" },
  { name: "RPG", description: "Deep stories, character progression, and immersive worlds.", icon: "Sparkles" },
  { name: "Adventure", description: "Explore vast worlds and unforgettable journeys.", icon: "Compass" },
  { name: "Racing", description: "Speed, stunts, and high-performance machines.", icon: "Gauge" },
  { name: "Sandbox", description: "Build, create, and play without limits.", icon: "Boxes" },
  { name: "Sports", description: "Authentic competition across the world's biggest sports.", icon: "Trophy" },
  { name: "Multiplayer", description: "Team up or compete with players around the globe.", icon: "Users" },
] as const

export function getGame(slug: string): Game | undefined {
  return GAMES.find((g) => g.slug === slug)
}

export function getRelated(game: Game, count = 4): Game[] {
  return GAMES.filter((g) => g.slug !== game.slug && g.categories.some((c) => game.categories.includes(c))).slice(0, count)
}

export const featuredGames = GAMES.filter((g) => g.featured)
export const trendingGames = GAMES.filter((g) => g.trending)
export const mobileGames = GAMES.filter((g) => g.mobile)
